# Generated by Django 4.2.4 on 2023-08-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0004_usuario_cpf_usuario_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.BigIntegerField(),
        ),
    ]
