# Generated by Django 4.2.4 on 2023-08-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0006_remove_usuario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.BooleanField(default='cpf'),
            preserve_default=False,
        ),
    ]
